extends:
  - airbnb-base
  - plugin:jest/recommended
env:
  node: true
  jest: true
rules:
  import/extensions: ["error", "ignorePackages"]
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
  no-trailing-spaces: error
  eol-last: ["error", "always"]
  comma-dangle: ["error", "always-multiline"]